mongoDB setup
MateuszWoj-bit/nodejs-homework pull request #3
Opened 2023-04-18 12:23 UTC by MateuszWoj-bit

2023-05-04 10:18 UTC, RadziuMM requested changes

2023-05-04 10:18 UTC, RadziuMM commented on routes/api/contactsMethods.js
> -  const schema = Joi.object({
Walidacja JOI powinna zostać i dopiero jak przejdzie request walidację powinien być dodany użytkownik do db

2023-05-04 10:18 UTC, RadziuMM commented on routes/api/contactsMethods.js
> -  const schema = Joi.object({
Walidacja JOI powinna zostać i dopiero jak przejdzie request walidację powinien być zmieniony użytkownik w db

2023-05-04 10:18 UTC, RadziuMM commented on routes/api/contactsMethods.js
> +  if (!body.favorite & body.favorite !==false) {
I to też powinno być sprawdzane w JOI

2023-05-04 18:21 UTC, MateuszWoj-bit commented on routes/api/contactsMethods.js
> -  const schema = Joi.object({
Walidacja przywrócona

2023-05-04 18:21 UTC, MateuszWoj-bit commented on routes/api/contactsMethods.js
> -  const schema = Joi.object({
Walidacja przywrócona

2023-05-04 18:21 UTC, MateuszWoj-bit commented on routes/api/contactsMethods.js
> +  if (!body.favorite & body.favorite !==false) {
Walidacja dodana

2023-05-08 18:13 UTC, RadziuMM approved these changes

2023-05-08 18:40 UTC, merged