Hw04 auth
MateuszWoj-bit/nodejs-homework pull request #4
Opened 2023-05-08 18:44 UTC by MateuszWoj-bit

2023-05-09 20:06 UTC, RadziuMM requested changes
Ogólnie jeszcze takie info co do komentarzy.
np.tu
    // Return success response
    return res.status(201).json({
    
Komentarz tego typu można porównać do tego jak byś zaprosił gości do domu, pokazywał im kuchnie wskazał na stół i powiedział "To jest stół, przy nim jemy posiłki". Każdy to wie i uznał by to za dziwne. Zazwyczaj jeśli komentujesz to to co jest nie jasne, a jeśli jest nie jasne to znaczy że zwaliłeś kod i trzeba go przepisać jeszcze raz. Ergo komentarzy należy unikać.

2023-05-09 20:06 UTC, RadziuMM commented on middleware/auth.js
> +function auth(req, res, next) {
Sprawdź w konspekcie jak jest zrobiona strategia jwt (passport-jwt). Tu jeszcze dodam że należy również sprawdzić czy wysyłany token jwt jest równy tokenowi zapisanemu w bazie (By potem nie było że się wylogowujesz i nadal możesz tym tokenem sprawdzać /current).

2023-05-09 20:06 UTC, RadziuMM commented on routes/api/registration.js
> +router.get("/users/current", auth, async (req, res) => {
Tu wychodzi teraz /users/users/current

2023-05-09 20:06 UTC, RadziuMM commented on routes/api/db/contactsSchema.js
> +// const mongoose = require("mongoose");
Nie trzymaj zakomentowanego kodu. Jeśli będziesz chciał do czegoś wrócić to możesz się gitem cofnąć do commita, lub nawet usunąć zmiany które wprowadził.

2023-05-10 13:43 UTC, MateuszWoj-bit commented on routes/api/db/contactsSchema.js
> +// const mongoose = require("mongoose");
Usunięty cały zakomentowany kod.

2023-05-10 13:43 UTC, MateuszWoj-bit commented on routes/api/registration.js
> +router.get("/users/current", auth, async (req, res) => {
Ścieżka poprawiona.

2023-05-10 13:44 UTC, MateuszWoj-bit commented on middleware/auth.js
> +function auth(req, res, next) {
Zmieniona strategia na konspektową i wprowadzona weryfikacja tokena.

2023-05-10 20:06 UTC, RadziuMM approved these changes

2023-05-10 21:01 UTC, merged